export const TOPICS = [
    { id: 9, name: "General Knowledge" },
    { id: 17, name: "Science & Nature" },
    { id: 21, name: "Sports" },
    { id: 23, name: "History" },
    { id: 12, name: "Music" },
    { id: 14, name: "Television" },
    { id: 10, name: "Books" },
    { id: 11, name: "Film" },
    { id: 15, name: "Video Games" },
    { id: 18, name: "Computers" },
    { id: 22, name: "Geography" },
    { id: 27, name: "Animals" },
    { id: 20, name: "Mythology" },
  ];